# Generated by Django 3.0.2 on 2020-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, help_text='150px150px', upload_to='images/articles/'),
        ),
    ]
